### ISSUE TITLE
Is this a place holder for the muli-media player?

### ISSUE THREAD

**Issue by mankev** [wet-boew/wet-boew-multimedia-fallback#1]
Is this a place holder for the muli-media player or just the fallback.

**Comment by mgifford** [comment]
I'd also like to see the code.  As well as some comparisons with existing HTML5 projects with fallbacks like:
http://www.longtailvideo.com/players
http://www.mediaelementjs.com/

**Comment by LaurentGoderre** [comment]
this is just the flash part
