### ISSUE TITLE
Duplicate IDs on the example page. 

### ISSUE THREAD

**Issue by mankev** [wet-boew/wet-boew-multimedia-fallback#12]
Duplicate IDs are created by the auto generated html when more than one player is present on the page. As such,  in IE8, only the first example will play on the Multimedia example page. Firefox fails on the third example even though MP4 is supported in later versions of Firefox. This latter case may not be due to the multiple IDs since we are experiencing the same problem on our web site with a single player on the page.

All players on the page works with Chrome and IE 10.

**Comment by LaurentGoderre** [comment]
Hi @mankev, this is not the right repo, this is only for the flash portion. That being said I had fix this id problem in a branch I was working on but didn't bring it in the right place.

**Comment by LaurentGoderre** [comment]
I opened a PR on the core project to fix this

**Comment by mankev** [comment]
OK, thanks Laurent.

**Comment by LaurentGoderre** [comment]
Fixed in the latest code.
