### ISSUE TITLE
Better Docs

### ISSUE THREAD

**Issue by mgifford** [wet-boew/wet-boew-multimedia-fallback#7]
Would be great to have better docs as to what this code does and how to set it up.  I'd also like to know how it differs from HTML5 video tools like jwplayer or Media Element JS.

**Comment by LaurentGoderre** [comment]
Hi @mgifford this is not meant to be a standalone project but rather a place to control the source for the Flash portion of the WET multimedia player. The output of this goes to the WET project in js/binary/

**Comment by mgifford** [comment]
Ok. This is good to know. It would still be good to better docs so that this is clear.

I'd also like to see how the solution compares with stand alone solutions.

As you know video delivery is complicated and evolving quickly.

**Comment by LaurentGoderre** [comment]
Of course I'm jaded but I believe the code for this is more lightweight. The only thing this does is emulate the HTML5 media API.

**Comment by mgifford** [comment]
We just implemented http://www.cpac.ca and it would be an interesting test case to do a comparison between what you've built & what we were able to do leveraging JW Player.  I really wish JW Player was GPL, but still find the ability to deal with multi-lingual audio streams to be pretty sophisticated.  

Is there a demo up yet for testing?  Did you go with WemM or MP4 for HTML5?

**Comment by LaurentGoderre** [comment]
There are working example for the video and audio player.

The project is not restricting the format but MP4 and webm are recommended. MP4 is the minimum.

http://wet-boew.github.com/wet-boew/demos/multimedia/multimedia-eng.html
http://wet-boew.github.com/wet-boew/demos/multimedia/multimedia-audio-eng.html

**Comment by mgifford** [comment]
It's a definite improvement from the last time I looked.  Great that it works on the iPad too.

**Comment by LaurentGoderre** [comment]
There's a lot of not so visible improvements to it. It's the first widget to use SVG icons, which means the whole UI is completely skinnable through CSS for browsers that support SVG.

**Comment by mgifford** [comment]
That's really excellent too. SVG is just such a great scalable format.  Much better supported these days too http://caniuse.com/#search=svg
