### ISSUE TITLE
Serving multimedia.swf from IIS with Request Filtering enabled

### ISSUE THREAD

**Issue by NeilEcker** [wet-boew/wet-boew-multimedia-fallback#8]
By default, the Request Filtering in IIS 7.0 has a hidden segment named 'bin' which prevents the multimedia.swf file located in /build/js/bin used for the fallback video player from being served.  If you do not have a bin folder in your site this hidden segment can be removed, otherwise the folder name should be changed to something not containing 'bin'.

**Comment by LaurentGoderre** [comment]
This was fixed in v3.0.1
